### Q1. Create one variable containing following type of data:

(i)	    string
(ii)	list
(iii)	float
(iv)	tuple

#### Solution

In [2]:
string_data="Data_Sience_Master_2.0"
List_data=[2.0,'Data_Science',True]
float_data=4.678
tuple_data=("Data_Sience_Master_2.0",1,'Master',4.67)
print("String Data:",string_data,"\nList Data:",List_data,"\nFloat Data:","float_data","\nTuple Data:",tuple_data)

String Data: Data_Sience_Master_2.0
List Data: [2.0, 'Data_Science', True]
Float Data: float_data
Tuple Data: ('Data_Sience_Master_2.0', 1, 'Master', 4.67)

### Q2. Given are some following variables containing data:

(i)	    var1 = ‘ ‘

(ii)	var2 = ‘[ DS , ML , Python]’

(iii)	var3 = [ ‘DS’ , ’ML’ , ‘Python’ ]

(iv)	var4 = 1.


What will be the data type of the above given variable

#### Solution

In [3]:
var1 = ''
var2 = '[ DS , ML , Python]'
var3 = ['DS' , 'ML' , 'Python']
var4 = 1.


# Date types of var1 is string
print("Data Type of var1:",type(var1))
# Date types of var2 is string
print("Data Type of var2:",type(var2))
# Date types of var3 is list
print("Data Type of var3:",type(var3))
# Date types of var4 is float
print("Data Type of var4:",type(var4))

Data Type of var1: <class 'str'>
Data Type of var2: <class 'str'>
Data Type of var3: <class 'list'>
Data Type of var4: <class 'float'>

### Q3. Explain the use of the following operators using an example:

(i)	    /

(ii)	% 

(iii)	//

(iv)	**

#### Solutions:
 - (i) / This operator is division operator it is used when we want to calcuate division of two numbers
##### Example:

In [4]:
first_number=34
second_number=3
result=first_number/second_number
print("Division of {0} and {1} is {2}".format(first_number,second_number,result))

Division of 34 and 3 is 11.333333333333334

- (2) % This operator is a Modulo operator it is used when we want to get the reminder after deviding the two numbers
##### Example:

In [5]:
first_number=34
second_number=3
result=first_number%second_number
print("Reminder of {0} and {1} is {2}".format(first_number,second_number,result))

Reminder of 34 and 3 is 1

- (3) // This operator is a floor devision operator it is used when we want to round the result down to the nearest whole number after deviding the two numbers.
##### Example:

In [6]:
first_number=34
second_number=3
result=first_number//second_number
print("Round of {0} and {1} is {2}".format(first_number,second_number,result))

Round of 34 and 3 is 11

- (4) ** This operator is a Exponent operator it is used to perform the exponent arithmetic in python.
##### Example:

In [9]:
first_number=34
second_number=3
result=first_number**second_number
print("Exponential of {0} and {1} is {2}".format(first_number,second_number,result))

Exponential of 34 and 3 is 39304

### Q4.Create a list of length 10 of your choice containing multiple types of data. Using for loop print the element and its data type.

In [17]:
List_val=['Master',1,5.6,True,[4,6,7],(5,6,9),'Data_Science',56,4,'[3,5,6]']

#Check the length of List_val
print("Length:",len(List_val))

for i in List_val:
    print("Element:",i,"\nData Types:",type(i),"\n----------------------------")

Length: 10
Element: Master
Data Types: <class 'str'>
----------------------------
Element: 1
Data Types: <class 'int'>
----------------------------
Element: 5.6
Data Types: <class 'float'>
----------------------------
Element: True
Data Types: <class 'bool'>
----------------------------
Element: [4, 6, 7]
Data Types: <class 'list'>
----------------------------
Element: (5, 6, 9)
Data Types: <class 'tuple'>
----------------------------
Element: Data_Science
Data Types: <class 'str'>
----------------------------
Element: 56
Data Types: <class 'int'>
----------------------------
Element: 4
Data Types: <class 'int'>
----------------------------
Element: [3,5,6]
Data Types: <class 'str'>
----------------------------

### Q5. Using a while loop, verify if the number A is purely divisible by number B and if so then how many times it can be divisible.

In [24]:
#To check a number is divisble by other number then we need to use Modulo Operator if Reminder is 0 then that numbers are purely divisible

first_nu=24
second_nu=2
count=0
tempfirst_nu=first_nu
while tempfirst_nu%second_nu==0:
    tempfirst_nu=tempfirst_nu//second_nu
    count+=1
if count==0:
    print("{0} is not divisible by {1}".format(first_nu,second_nu))
else:
    print("{1} is divisible by {2} and can be divided {0} times.".format(count,first_nu,second_nu))

24 is divisible by 2 and can be divided 3 times.

### Q6. Create a list containing 25 int type data. Using for loop and if-else condition print if the element is divisible by 3 or not

In [25]:
#creating a list containting 25 int type data using for loop
list_data=[]
for i in range(1,26):
    list_data.append(i)

#checking number is divisible by 3 or not
for i in list_data:
    if i%3==0:   #if reminder is 0 then first number is divisible by 3
        print(f"{i} is divisible by 3")
    else:
        print(f"{i} is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is divisible by 3
4 is not divisible by 3
5 is not divisible by 3
6 is divisible by 3
7 is not divisible by 3
8 is not divisible by 3
9 is divisible by 3
10 is not divisible by 3
11 is not divisible by 3
12 is divisible by 3
13 is not divisible by 3
14 is not divisible by 3
15 is divisible by 3
16 is not divisible by 3
17 is not divisible by 3
18 is divisible by 3
19 is not divisible by 3
20 is not divisible by 3
21 is divisible by 3
22 is not divisible by 3
23 is not divisible by 3
24 is divisible by 3
25 is not divisible by 3

### Q7. What do you understand about mutable and immutable data types? Give examples for both showing this property

#### Mutable:
- Mutable means after creating a variable with some values and later we can change the values i.e update the values,delete the values and insert the values
- Example: List
#### Immutable:
- Immutable menas after creating a variable with some value and later we can not change the vlaue 
- Example: String,Tuple

#### Example:

In [30]:
# Mutable:
list_value=['Master',1,5.6,True,[4,6,7],(5,6,9),'Data_Science',56,4,'[3,5,6]']
#lets change the Master to Data
list_value[0]="Data"
#add science in last of the list_value
list_value.append("Science")
print(list_value)

['Data', 1, 5.6, True, [4, 6, 7], (5, 6, 9), 'Data_Science', 56, 4, '[3,5,6]', 'Science']

In [28]:
# Immutable:
list_value=('Master',1,5.6,True,[4,6,7],(5,6,9),'Data_Science',56,4,'[3,5,6]')
#lets change the Master to Data
list_value[0]="Data"    #This will show error
print(list_value)

TypeError: 'tuple' object does not support item assignment

#### Above code is showing error means we can not change the immutable variable values